### PR TITLE
Attempt to support C/C++; added Portuguese translation

### LINKED ISSUE #11: Feature request: allow more programming languages!
At least C/C++ (and a few variants) could be easily added, I think.

In fact, I'm submitting a PR :)

### PR DESCRIPTION
**Pull request by GwynethLlewelyn**
This is a bare-bones, quick & dirty support for C/C++ (as well as the obscure [Linden Scripting Language](https://extensions.panic.com/extensions/gwynethllewelyn/gwynethllewelyn.LindenScriptingLanguage/) (LSL), used only on the virtual world platforms [Second Life®](https://secondlife.com) and [OpenSimulator](http://opensimulator.org), and which has similar syntax); basically I just used the PHP parser, with (so far) a single tweak — disallow `$` as a valid character in variable names.

As a bonus, I've noticed that the German translation lacked a few lines (possibly present only in more recent versions, which didn't get the chance to be translated — yet). Please review them; while I'm allegedly fluent in German, I'm in reality _extremely_ rusty 🙂 I also attempted to keep some consistency with the existing translated strings.

Since my mother language is Portuguese, I also quickly added the full (European) Portuguese translation 😁  At the very least, you can reuse that file from this PR. Ironically, I did _not_ test it, since I've configured Nova to show everything in English only! But it should work 😹 

I don't know how exactly you wish us to do PR submissions. At the time of writing, v0.6.1 is current, and it seems that you're actively working on v0.6.2. So I sort of bumped it to v0.6.3 — feel free to change the numbering according to your preferences. Perhaps it could be a v0.6.3-beta instead?

Or perhaps you wish to go straight to v0.7.0, even taking into account that the C/C++/LSL quick patch is in the earliest stages (and not fully tested anyway)...

Closes #11.

### CODE REVIEW

**Comment by maxgrafik** [comment]
Thanks for the contribution 😃 
I will definitely include your Portuguese translation. For the C/C++ parser however, it's a bit more complicated. We can’t just repurpose the PHP parser. I had a look at the [original code](https://github.com/nikhilkalige/docblockr) and it’s C++ parser today. The RegExp is quite different. I made a first attempt to port this for Nova. You may want to have a look at the [cpp-parser branch](https://github.com/maxgrafik/DocBlockr.novaextension/tree/cpp-parser).
Unfortunately I have no experience with C/C++, I only did some basic tests and it seems to work. But there may be more complex constructs for which the parser may fail.

**Comment by GwynethLlewelyn** [comment]
Aye, I'm aware C++ is _very_ different than PHP — and orders and orders of magnitude more complex. I've got little-to-zero experience with C/C++ — I only did some 'serious' work in C++ over a quarter of a century ago, when C++ had just come out, and was a much tamer beast than the monster it is today 🤣 I'm almost sure that the parser _will_ fail in many situations; it's naïve to believe otherwise.

However, now and then I happen to come across some C/C++ code that needs fixing or patching, and it's always nice to have your extension doing the DocBlock magic on those files 😀 And, as you noticed, the 'basics' work (sort of!), which is more than enough for my tinkering purposes.

Also, in any case, with the aid of the current-generation LSPs, C++ headers practically self-document themselves anyway 😆 DocBlocks are so much more important on languages with very loose typing, such as PHP or JavaScript, where it makes sense to document what the parameters are supposed to _do_... but I digress. I cannot promise to delve deep into the original docblockr RegExps to see if I can adapt them to your extension; that might really be way beyond my current skills! But it doesn't hurt to take a peek and see if I can grasp the essentials...

**Comment by maxgrafik** [comment]
I had a look at [cppreference.com](https://cppreference.com) the other day. And yes, the C++ parser will *definitely* fail sooner or later 🤣 I guess using RegExp to parse a language is already broken by design.

However, I needed something to document my code and the original DocBlockr package seemed to be rather easy to port to Nova. Although I barely understand the more complicated regex' myself. I just hoped they would work 😆 

So, to add some more languages to DocBlockr I also ported the Java, ObjC/ObjC++ and Rust parsers these days. Will release the updated extension soon.

**Comment by maxgrafik** [comment]
I'm closing this as C/C++ is now included in the latest version

**Pull request closed without merging**
